title: Daemon Engineer blog
email: tsdaemon@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Science and education enthusiasts blog. Stories and tutorials about deep learning,
   natural language processing, data visualization and software development.

facebook_username: anatolii.stn # replace by your username
github_username:  tsdaemon

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-scholar

disqus:
  shortname: anatoliis-blog

google_analytics: UA-104247978-1

exclude:
  - notebooks/

scholar:
  style: mla

include: ['courses']

header_pages:
  - about.md
  - courses.md
